### ISSUE TITLE
version compatibility

### ISSUE THREAD

**Issue by thesquaremedia** [nab-velocity/woocommerce-plugin#11]
is there any intent to support the latest version of woocommerce 2.6.1? or any other later version? 2.2.11 seems like an old version of woocommerce.

**Comment by yassernasr** [comment]
It does work with 2.6.1, we just confirmed.

On Tuesday, June 28, 2016, The Square Media notifications@github.com
wrote:

> is there any intent to support the latest version of woocommerce 2.6.1? or
> any other later version? 2.2.11 seems like an old version of woocommerce.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nab-velocity/woocommerce-plugin/issues/11, or mute
> the thread
> https://github.com/notifications/unsubscribe/AFl1XUJEyQQ7IHilTmQRPc88BA-SMUm1ks5qQUvRgaJpZM4JASaq
> .

## 

Kindest Regards,

Yasser

**Comment by thesquaremedia** [comment]
ok great thanks im about to install it on the latest version of woo and wp if anything ill reply with findings

**Comment by thesquaremedia** [comment]
Hi, so far all i can see is that the name of the extension creates a conflict as there is another extension in the wordpress repo named velocity so it prompted me to update the plugin which ended up installing another extension. i had to change the commented line on the plugin main php file to avoid this problem. also is there any possibility of having the extension work with https://woocommerce.com/products/woocommerce-subscriptions/ or do you have any documentation for me to implement this?
